# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "868557ed2035e3e4c12d0069c307a6e3"
name = "i95Dev B2B"
application_url = "https://meter-influenced-census-displays.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_companies,read_customers,read_orders,read_products,read_script_tags,read_themes,unauthenticated_read_product_listings,write_companies,write_content,write_customers,write_discounts,write_online_store_navigation,write_orders,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [ "https://meter-influenced-census-displays.trycloudflare.com/api/auth" ]

[app_proxy]
url = "/apps/quick-order"
subpath = "quick-order"
prefix = "apps"
